### ISSUE TITLE
Maybe the location of touch is not correct

### ISSUE THREAD

**Issue by hengying** [fbiego/CST816S#3]
My touch chip is CST816T.
I tried this library, it works well, except that the y position is always less than 255.

According to the datasheet, maybe x and y should be:

  data.x = data_raw[2] & 0xF;
  data.x = (data.x << 8) +  data_raw[3];

  data.y = data_raw[4] & 0xF;
  data.y = (data.y << 8) + data_raw[5];

**Comment by JohnTaipei** [comment]
@hengying 
good job
your solution works

**Comment by Arielhh** [comment]
> data.x = data_raw[2] & 0xF; data.x = (data.x << 8) + data_raw[3];
> 
> data.y = data_raw[4] & 0xF; data.y = (data.y << 8) + data_raw[5];

where do you need to change the code with the above fix?
